- pygorithm/sorting/bubble_sort.py
Feel free to discard this changes if you want to keep your code simple. This changes just match the pseudo-code of the wikipedia page of bubble sort.
> Update to Bubble Sort

- .gitignore
- tests/test_searching.py
- tests/test_sorting.py
Unit tests can now be run with `python -m unittest discovery` or `python -m unittest discovery -s tests`. I also update some of the formating in both test files.
> Updated unittests to run with unittest command

- tests/test_data_structure.py
Add a few tests for a null stack.
> Null stack test

- pygorithm/data_structures/linked_list.py
when the head.next is none, but the head.data == data, it not work
> fix the bug on SinglyLinkedList.delete

- pygorithm/searching/quickselect.py
Need to write tests + double check complexities
> Added quickselect algorithm

- pygorithm/data_structures/heap.py
- tests/test_data_structure.py
Fixed issue #21 
- added more comprehensive data for test
- made tests PEP 263 compatible with utf-8 encoding
- added Big O time complexities for insert and pop
> Heap Implementation

- docs/Fibonacci.rst
- pygorithm/fibonacci/__init__.py
- pygorithm/fibonacci/generator.py
- pygorithm/fibonacci/goldenratio.py
- pygorithm/fibonacci/memoization.py
- pygorithm/fibonacci/modules.py
- tests/test_fibonacci.py
Hello,
I added two new implementations of Fibonacci logic via `generator` and `math (golden ratio)`.
Also I went ahead and refactored some code.
**DONE**:
> Fibonacci: golden ratio, generator

- pygorithm/sorting/bubble_sort.py
Best case for bubble sort is O(n).
reference:  [cheat](http://bigocheatsheet.com)
> best case for Bubble sort

- pygorithm/math/lcm_using_gcd.py
- tests/test_math.py
* I have implemented lcm using gcd.
* Also updatedunit test module
> LCM using gcd

- CONTIRBUTORS.md
- docs/Data_Structure.rst
- docs/Pathing.rst
- docs/index.rst
- pygorithm/__init__.py
- pygorithm/data_structures/graph.py
- pygorithm/pathing/__init__.py
- pygorithm/pathing/dijkstra.py
- tests/test_data_structure.py
- tests/test_pathing.py
First two commits:
This adds a test that shows why the current implementation fails and then
fixes it. The old tests passed but were not doing what they implied they
were doing.
Later commits:
Add dijkstra pathfinding (see commit notes for more details) with documentation and tests
> Add dijkstra pathfinding

- README.rst
- docs/Data_Structure.rst
- docs/Fibonacci.rst
- docs/Searching.rst
- docs/Sorting.rst
- docs/index.rst
- pygorithm/__init__.py
- pygorithm/pathfinding/astar.py
- pygorithm/pathfinding/dijkstra.py
- README.rst
- Syntax updates
- Updates examples
- docs
- Removed unnecessary info at end of examples
- Updates syntax to remove camel casing
- __init__.py
- Updated pathing to pathfinding
- Pathfinding
- dijkstra.py
- Added header docstrings to top of file
- Minor syntax changes
- Added missing import: inspect
- Updated reverse_path() to be static
- Removed 'self' parameter from get_code()
- Updated variable 'open' in find_path() to '_open' to prevent shadowing built-in open() function
- astar.py
- Added header docstrings to top of file
- Minor syntax changes, PEP8
- Updated lines where they where longer than 125 chars (PEP8)
- Added missing import: inspect
- Updated reverse_path() to be static
- Removed 'self' parameter from get_code()
- Updated variable 'open' in find_path() to '_open' …
> Syntax and README updates!

- pygorithm/searching/interpolation_search.py
Added Interpolation Search algorithm.
Might need a try/except block.
> Added interpolation_search

- pygorithm/__init__.py
- pygorithm/dynamic_programming/binary_knapsack.py
- pygorithm/greedy_algorithm/__init__.py
- pygorithm/greedy_algorithm/fractional_knapsack.py
Created a greedy algorithm folder with fractional knapsack and minor
changes to binary knapsack code.
> Added fractional knapsack and minor changes

- pygorithm/data_structures/trie.py
To keep uniform with the rest of the files, I am adding myself as the author of `trie.py`.
> Author of Trie

- pygorithm/sorting/__init__.py
- pygorithm/sorting/radix_sort.py
- tests/test_sorting.py
Implemented Radix Sorting based of submission from @ashaywalke
Implemented Radix Sorting unittests
> Implemented Radix Sorting, thanks @ashaywalke

- CONTIRBUTORS.md
- pygorithm/__init__.py
Updated CONTRIBUTORS.md
Updated __init__.py
> Minor Updates

- pygorithm/data_structures/tree.py
I added insert and counting-node functions for BinaryTree and BinarySearchTree.
Please let me know if you have any feedback
> Add insert and count-nodes

- pygorithm/data_structures/linked_list.py
> Issue#88 - Fixed

- pygorithm/sorting/brick_sort.py
- pygorithm/sorting/cocktail_sort.py
- pygorithm/sorting/gnome_sort.py
- pygorithm/sorting/tim_sort.py
- tests/test_sorting.py
This effectively standardizes the function arguments for all the new
sorting algorithms to be consistent with the other ones. Also fixes a few
bugs and performs some style improvements, such as moving documentation
of functions to after the function definition instead of before, and
adding documentation where it is missing.
> Add tests and improve documentation on new sorting algorithms

- pygorithm/dynamic_programming/fractional_knapsack.py
- pygorithm/dynamic_programming/longest_palindrome_substring.py
Adding two algorithms for others to use.
1) Fractional Knapsack which gives the weight of the items infractions to be put in the knapsack.
2) Longest Palindrome Substring which gives the longest palindrome substring.
> Adding Two Algorithms
